# Generated by Django 2.2.5 on 2019-09-15 12:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190915_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1200, null=True),
        ),
    ]
