# Generated by Django 2.2.5 on 2019-09-15 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20190915_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
