# Generated by Django 2.2.5 on 2019-09-15 12:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20190915_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=325, null=True),
        ),
    ]
